apiVersion: v1
kind: Secret
metadata:
  name: user-service-secrets
  namespace: ecommerce
type: Opaque
stringData:
  GOOGLE_CLIENT_ID: "${GOOGLE_CLIENT_ID}"
  GOOGLE_CLIENT_SECRET: "${GOOGLE_CLIENT_SECRET}"
